GET http://localhost:3001/api/notes
###

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuaXNoMDEyMyIsImlkIjoiNjQ4OGExZTNkMDUxNTU3MGMyMDA2YjcyIiwiaWF0IjoxNjg2NzU4NDcxfQ.gyY-PJajPK9_MBE-kzmGAJh6O7Oc8coRRq6h7yv7

{
    "content" : "working on error functions",
    "important" : true
}